version: '3'
services:
  app:
    container_name: pukpao-shop
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    depends_on:
      - pukpao-mysql
  nginx:
    container_name: reverse-proxy
    image: nginx:1.17
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
  pukpao-mysql:
    container_name: pukpao-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: pukpao_shop
      MYSQL_ROOT_PASSWORD: passwordkz
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    restart: always
